services:
  db:
    image: postgres:13
    container_name: roster_db
    environment:
      POSTGRES_DB: roster_db
      POSTGRES_USER: roster_user
      POSTGRES_PASSWORD: roster_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: roster_parser
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_NAME=roster_db
      - DB_USER=roster_user
      - DB_PASSWORD=roster_password

volumes:
  db_data:
